devices:
- "/dev/input/event20"
baseMouseSpeed: 700.0
baseScrollSpeed: 15.0
layers:
# the first layer is active at start
- name: initial
  bindings:
    # when tab is held and another key pressed, activate mouse layer
    space: tap-hold-next space; toggle-layer mouse ; 500
- name: mouse
  # when true, keys that are not mapped keep their original meaning
  passThrough: true
  bindings:
    esc: layer initial
    r: reload-config
    d: move  1  0
    a: move -1  0
    s: move  0  1
    w: move  0 -1
    z: scroll up
    c: scroll down
    leftalt: speed 4.0
    leftshift: speed 0.25
    q: button left
    e: button right
