devices:
- "/dev/input/event4"
- "/dev/input/event14"
- "/dev/input/by-id/usb-04d9_USB-HID_Keyboard-event-kbd"
# - "/dev/input/by-id/usb-Keychron_Keychron_K6-event-kbd"
startCommand: "xset r rate 250 35"
baseMouseSpeed: 950.0
baseScrollSpeed: 15.0
layers:
# the first layer is active at start
- name: initial
  bindings:
    # when space is held and another key pressed, activate mouse layer
    space: tap-hold space; toggle-layer mouse ; 250
- name: mouse
  # when true, keys that are not mapped keep their original meaning
  passThrough: true
  bindings:
    esc: layer initial
    r: reload-config
    d: move  1  0
    a: move -1  0
    s: move  0  1
    w: move  0 -1
    z: scroll up
    c: scroll down
    leftalt: speed 4.0
    leftshift: speed 0.35
    q: button left
    e: button right
